### PR TITLE
Add swapi data

### LINKED ISSUE #3: Data source idea: StarWars API
also via @masalmon

https://swapi.co

### PR DESCRIPTION
**Pull request by cwickham**
This pull request adds  the lists `sw_people`, `sw_films`, `sw_species`, `sw_planets`, `sw_starships` and `sw_vehicles` and fixes #3 

PR includes code to generate lists, basic documentation and tests (based on those already present).

`devtools::check()` finished with:
```
Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes
```

### CODE REVIEW

**Comment by cwickham** [comment]
@jennybc Any chance of incorporating this? I'd love to use repurrrsive rather than relying on students downloading data in an upcoming tutorial (June 3).

**Comment by jennybc** [comment]
Oh yes! Sorry! I read the original notification and then it slid off my radar.

Do you want this on CRAN by then or just GitHub? @hadley and I talked about maybe putting some of these examples into purrr itself (I think we did?), but that train is leaving the station....

**Comment by hadley** [comment]
There will be another purrr release in about a month, but that's probably cutting it a bit fine for @cwickham's tutorial.

**Comment by jennybc** [comment]
OK @cwickham I'm happy to merge in here, regardless.

If we think the examples are destined to find a home in purrr, we could leave this as a GitHub package for now. But `install.packages()` is awfully nice in a workshop. Let me know your thoughts.

**Comment by cwickham** [comment]
Thanks!  I'm ok with installing from github for now, I can probably get most people to do that beforehand.  

@hadley I remember seeing some starwars data in a tidyverse package recently, but in tibble form not nested list form.  Is this something you want to add to purrr?  If so, I can do a PR for a future release.

**Comment by hadley** [comment]
Yeah dplyr has a reduced form with a couple of list cols. A full nested list treatment would be great for purrr, or it might be big enough for it's own package. I was thinking it might be useful to have the starwars data in a few forms: original nested lists, tibbles with list-cols, full relational with 1-to-many joins.

**Comment by jennybc** [comment]
Of the content I already had here in repurrrsive, I think the Game of Thrones data has similar potential as Star Wars and could go into a CRAN package. Into purrr or a package for teaching data manipulation. Unless the idea is to isolate just Star Wars and in which I guess I will play Game of Thrones by myself. Or they could be executed in parallel as two similar packages that support all manner of wrangling exposition.

FWIW I also include the Game of Thrones data here as JSON and XML to support teaching data import from something other than rectangular/csv.
 
The GitHub data and colour palettes were mildly useful in the purrr tutorial but probably not worth putting in a CRAN package.

**Pull request merged**
